### ISSUE TITLE
Sick Stache Error when connecting to Sickrage

### ISSUE THREAD

**Issue by xGBHxPegasus** [Buttink/sick-stache#35]
Hey.

I recently moved over from Sickbeard Alpha torrents to Sickrage and noticed that my sickstache has stopped working after reconfiguring it to the new Sickrage.

Had it running find with Sickbeard Alpha torrents but whatever I do I cannot seem to get it to work with Sickrage.

The error message I get on my S5 is:

Error Retrieving Results
Error: java.lang.IllegalStateException: Expected
BEGIN_OBJECT but was STRING at line 1 column 1
Path $

I did some googling and found others with a simliar message but with column 10 not 1 and I have tried adding api to the extra path which hasn't fixed it either.

Is this an issue with the app or something I may have configured wrong with Sickrage?

**Comment by Buttink** [comment]
Does this fix it? https://github.com/Buttink/sick-stache/issues/24

**Comment by xGBHxPegasus** [comment]
Unfortunately not, I've tried adding api, /api, /api/, api/.

Had a good hour of googling and changing things yesterday but couldn't get it to work

Although no all of a sudden i'm getting the below error...

Error Retrieving Results
ERROR: Illegal character in authority at index 23:http://MYURL:8081///api/**********/?cmd=shows

**Comment by xGBHxPegasus** [comment]
Never mind. Back to the original error message now :(

**Comment by Buttink** [comment]
Hmm Well, I would double check that all the settings are correct for
sickstache. My only other guess would be to try to manually call one of the
api rest function in a web browser. You don't have any sort of https or
username password do you?

**Comment by xGBHxPegasus** [comment]
I have a username/password on but I've disabled it and tested and it didn't work either.

How would I manually call the api rest function? assuming its something like http://myurl.co.uk/api ?

**Comment by Buttink** [comment]
http://myurl.co.uk/api/1234567890/?cmd=sb.ping

replace 1234567890 with your actual api key and you should get something
like

{
    "data": {
        "pid": 13152
    },
    "message": "Pong",
    "result": "success"
}

I'm really sorry you have to do this to figure out the problem. :(

**Comment by xGBHxPegasus** [comment]
hmm tried that in a web browser (i assume its suppose to just go into the url bar like a normal web address) and it went straight into the "show list" page.

I feel its most likely going to be a Sickrage issue as it showed the following in the logs:

AAAttributeError: 'WebRoot' object has no attribute 'api/c53ab4fcdae9ded05e3e4474b158860e'
AA    method = getattr(self, route)
AA  File "C:\Users\MEDIASERVER\SickRage-master\sickbeard\webserve.py", line 214, in get
2015-02-18 18:44:09 DEBUG    TORNADO :: Failed doing webui request "api/c53ab4fcdae9ded05e3e4474b158860e": Traceback (most recent call last):
AA
AAAttributeError: 'WebRoot' object has no attribute 'api/c53ab4fcdae9ded05e3e4474b158860e'
AA    method = getattr(self, route)
AA  File "C:\Users\MEDIASERVER\SickRage-master\sickbeard\webserve.py", line 214, in get
2015-02-18 18:41:45 DEBUG    TORNADO :: Failed doing webui request "api/c53ab4fcdae9ded05e3e4474b158860e": Traceback (most recent call last):

**Comment by Buttink** [comment]
What....... I will admit I have SickRage, but its old. I probably won't
have time tonight to test it/figure it out though.

I would try to do /api/api/1234567890/?cmd=sb.ping see if that works
because that is what extra path does.

**Comment by MGaetan89** [comment]
In case it can help, I am also using SickRage (latest dev version), and http://myurl.com/api/key/?cmd=sb.ping works for me.
I don't have Sick-Stache configured at the moment, so I can't tell you if the application works for me thought.

**Comment by xGBHxPegasus** [comment]
No rush Buttink, Ive backed up my files and gonna go to the dev branch, see if that fixes it :)

Will see what happens.

**Comment by cplmayo** [comment]
I've hit this error as well, tried everything listed to fix but nothing has worked.

**Comment by apesch85** [comment]
I've also hit this error, let me know if there's anything I can do to help troubleshoot! =)

**Comment by Buttink** [comment]
/facepalm I completely forgot about this, and now I'm sick lol. I'll try to
fire up the app today and debug what is happening.

**Comment by xGBHxPegasus** [comment]
Hey buttink,

Did you manage to take a look at the issue? Had to stop using the app cause of it :(

**Comment by thenamelessthing** [comment]
Hi, I have the same problem too.

**Comment by thenamelessthing** [comment]
https://wiiworld.no-ip.org/owncloud/public.php?service=files&t=WnfOqoxE5Y36WT4

**Comment by thenamelessthing** [comment]
The warning on the link is normal because I have a self sign ssl certificat

**Comment by raver2046** [comment]
Samedi issue can you fix it?

**Comment by Microbz** [comment]
Same issue here. 
Fix in the future ?

**Comment by D4rk56** [comment]
Same issue

**Comment by Sillikk** [comment]
Hey! I still have the same issue. Is there a fix?
